/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedCompaniesRouteImport } from './routes/_authenticated.companies'
import { Route as AuthenticatedContactsRouteImport } from './routes/_authenticated.contacts'
import { Route as AuthenticatedCustomFieldsRouteImport } from './routes/_authenticated.custom-fields'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated.dashboard'
import { Route as AuthenticatedFlowsRouteImport } from './routes/_authenticated.flows'
import { Route as AuthenticatedInboxRouteImport } from './routes/_authenticated.inbox'
import { Route as AuthenticatedIntegrationsRouteImport } from './routes/_authenticated.integrations'
import { Route as AuthenticatedMediaRouteImport } from './routes/_authenticated.media'
import { Route as AuthenticatedSegmentsRouteImport } from './routes/_authenticated.segments'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated.settings'
import { Route as AuthenticatedTagsRouteImport } from './routes/_authenticated.tags'
import { Route as AuthenticatedTemplatesRouteImport } from './routes/_authenticated.templates'
import { Route as AuthIndexRouteImport } from './routes/auth.index'
import { Route as AuthForgotPasswordRouteImport } from './routes/auth.forgot-password'
import { Route as AuthResetPasswordRouteImport } from './routes/auth.reset-password'
import { Route as AuthenticatedInboxIndexRouteImport } from './routes/_authenticated.inbox.index'
import { Route as AuthenticatedInboxConversationIdRouteImport } from './routes/_authenticated.inbox.$conversationId'
import { Route as ApiPublicHooksAutomationEventRouteImport } from './routes/api/public/hooks/automation-event'
import { Route as ApiPublicHooksAutomationTickRouteImport } from './routes/api/public/hooks/automation-tick'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedCompaniesRoute = AuthenticatedCompaniesRouteImport.update({
  id: '/companies',
  path: '/companies',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedContactsRoute = AuthenticatedContactsRouteImport.update({
  id: '/contacts',
  path: '/contacts',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCustomFieldsRoute =
  AuthenticatedCustomFieldsRouteImport.update({
    id: '/custom-fields',
    path: '/custom-fields',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedFlowsRoute = AuthenticatedFlowsRouteImport.update({
  id: '/flows',
  path: '/flows',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedInboxRoute = AuthenticatedInboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedIntegrationsRoute =
  AuthenticatedIntegrationsRouteImport.update({
    id: '/integrations',
    path: '/integrations',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMediaRoute = AuthenticatedMediaRouteImport.update({
  id: '/media',
  path: '/media',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSegmentsRoute = AuthenticatedSegmentsRouteImport.update({
  id: '/segments',
  path: '/segments',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedTagsRoute = AuthenticatedTagsRouteImport.update({
  id: '/tags',
  path: '/tags',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedTemplatesRoute = AuthenticatedTemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => AuthRoute,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => AuthRoute,
} as any)
const AuthenticatedInboxIndexRoute = AuthenticatedInboxIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedInboxRoute,
} as any)
const AuthenticatedInboxConversationIdRoute =
  AuthenticatedInboxConversationIdRouteImport.update({
    id: '/$conversationId',
    path: '/$conversationId',
    getParentRoute: () => AuthenticatedInboxRoute,
  } as any)
const ApiPublicHooksAutomationEventRoute =
  ApiPublicHooksAutomationEventRouteImport.update({
    id: '/api/public/hooks/automation-event',
    path: '/api/public/hooks/automation-event',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksAutomationTickRoute =
  ApiPublicHooksAutomationTickRouteImport.update({
    id: '/api/public/hooks/automation-tick',
    path: '/api/public/hooks/automation-tick',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/companies': typeof AuthenticatedCompaniesRoute
  '/contacts': typeof AuthenticatedContactsRoute
  '/custom-fields': typeof AuthenticatedCustomFieldsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/flows': typeof AuthenticatedFlowsRoute
  '/inbox': typeof AuthenticatedInboxRouteWithChildren
  '/integrations': typeof AuthenticatedIntegrationsRoute
  '/media': typeof AuthenticatedMediaRoute
  '/segments': typeof AuthenticatedSegmentsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/tags': typeof AuthenticatedTagsRoute
  '/templates': typeof AuthenticatedTemplatesRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/': typeof AuthIndexRoute
  '/inbox/$conversationId': typeof AuthenticatedInboxConversationIdRoute
  '/inbox/': typeof AuthenticatedInboxIndexRoute
  '/api/public/hooks/automation-event': typeof ApiPublicHooksAutomationEventRoute
  '/api/public/hooks/automation-tick': typeof ApiPublicHooksAutomationTickRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/companies': typeof AuthenticatedCompaniesRoute
  '/contacts': typeof AuthenticatedContactsRoute
  '/custom-fields': typeof AuthenticatedCustomFieldsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/flows': typeof AuthenticatedFlowsRoute
  '/integrations': typeof AuthenticatedIntegrationsRoute
  '/media': typeof AuthenticatedMediaRoute
  '/segments': typeof AuthenticatedSegmentsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/tags': typeof AuthenticatedTagsRoute
  '/templates': typeof AuthenticatedTemplatesRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth': typeof AuthIndexRoute
  '/inbox/$conversationId': typeof AuthenticatedInboxConversationIdRoute
  '/inbox': typeof AuthenticatedInboxIndexRoute
  '/api/public/hooks/automation-event': typeof ApiPublicHooksAutomationEventRoute
  '/api/public/hooks/automation-tick': typeof ApiPublicHooksAutomationTickRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/_authenticated/companies': typeof AuthenticatedCompaniesRoute
  '/_authenticated/contacts': typeof AuthenticatedContactsRoute
  '/_authenticated/custom-fields': typeof AuthenticatedCustomFieldsRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/flows': typeof AuthenticatedFlowsRoute
  '/_authenticated/inbox': typeof AuthenticatedInboxRouteWithChildren
  '/_authenticated/integrations': typeof AuthenticatedIntegrationsRoute
  '/_authenticated/media': typeof AuthenticatedMediaRoute
  '/_authenticated/segments': typeof AuthenticatedSegmentsRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/tags': typeof AuthenticatedTagsRoute
  '/_authenticated/templates': typeof AuthenticatedTemplatesRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/': typeof AuthIndexRoute
  '/_authenticated/inbox/$conversationId': typeof AuthenticatedInboxConversationIdRoute
  '/_authenticated/inbox/': typeof AuthenticatedInboxIndexRoute
  '/api/public/hooks/automation-event': typeof ApiPublicHooksAutomationEventRoute
  '/api/public/hooks/automation-tick': typeof ApiPublicHooksAutomationTickRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/companies'
    | '/contacts'
    | '/custom-fields'
    | '/dashboard'
    | '/flows'
    | '/inbox'
    | '/integrations'
    | '/media'
    | '/segments'
    | '/settings'
    | '/tags'
    | '/templates'
    | '/auth/forgot-password'
    | '/auth/reset-password'
    | '/auth/'
    | '/inbox/$conversationId'
    | '/inbox/'
    | '/api/public/hooks/automation-event'
    | '/api/public/hooks/automation-tick'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/companies'
    | '/contacts'
    | '/custom-fields'
    | '/dashboard'
    | '/flows'
    | '/integrations'
    | '/media'
    | '/segments'
    | '/settings'
    | '/tags'
    | '/templates'
    | '/auth/forgot-password'
    | '/auth/reset-password'
    | '/auth'
    | '/inbox/$conversationId'
    | '/inbox'
    | '/api/public/hooks/automation-event'
    | '/api/public/hooks/automation-tick'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/companies'
    | '/_authenticated/contacts'
    | '/_authenticated/custom-fields'
    | '/_authenticated/dashboard'
    | '/_authenticated/flows'
    | '/_authenticated/inbox'
    | '/_authenticated/integrations'
    | '/_authenticated/media'
    | '/_authenticated/segments'
    | '/_authenticated/settings'
    | '/_authenticated/tags'
    | '/_authenticated/templates'
    | '/auth/forgot-password'
    | '/auth/reset-password'
    | '/auth/'
    | '/_authenticated/inbox/$conversationId'
    | '/_authenticated/inbox/'
    | '/api/public/hooks/automation-event'
    | '/api/public/hooks/automation-tick'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  ApiPublicHooksAutomationEventRoute: typeof ApiPublicHooksAutomationEventRoute
  ApiPublicHooksAutomationTickRoute: typeof ApiPublicHooksAutomationTickRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/companies': {
      id: '/_authenticated/companies'
      path: '/companies'
      fullPath: '/companies'
      preLoaderRoute: typeof AuthenticatedCompaniesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/contacts': {
      id: '/_authenticated/contacts'
      path: '/contacts'
      fullPath: '/contacts'
      preLoaderRoute: typeof AuthenticatedContactsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/custom-fields': {
      id: '/_authenticated/custom-fields'
      path: '/custom-fields'
      fullPath: '/custom-fields'
      preLoaderRoute: typeof AuthenticatedCustomFieldsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/flows': {
      id: '/_authenticated/flows'
      path: '/flows'
      fullPath: '/flows'
      preLoaderRoute: typeof AuthenticatedFlowsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/inbox': {
      id: '/_authenticated/inbox'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof AuthenticatedInboxRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/integrations': {
      id: '/_authenticated/integrations'
      path: '/integrations'
      fullPath: '/integrations'
      preLoaderRoute: typeof AuthenticatedIntegrationsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/media': {
      id: '/_authenticated/media'
      path: '/media'
      fullPath: '/media'
      preLoaderRoute: typeof AuthenticatedMediaRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/segments': {
      id: '/_authenticated/segments'
      path: '/segments'
      fullPath: '/segments'
      preLoaderRoute: typeof AuthenticatedSegmentsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/tags': {
      id: '/_authenticated/tags'
      path: '/tags'
      fullPath: '/tags'
      preLoaderRoute: typeof AuthenticatedTagsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/templates': {
      id: '/_authenticated/templates'
      path: '/templates'
      fullPath: '/templates'
      preLoaderRoute: typeof AuthenticatedTemplatesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/auth/': {
      id: '/auth/'
      path: '/'
      fullPath: '/auth/'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/forgot-password': {
      id: '/auth/forgot-password'
      path: '/forgot-password'
      fullPath: '/auth/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/reset-password': {
      id: '/auth/reset-password'
      path: '/reset-password'
      fullPath: '/auth/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_authenticated/inbox/': {
      id: '/_authenticated/inbox/'
      path: '/'
      fullPath: '/inbox/'
      preLoaderRoute: typeof AuthenticatedInboxIndexRouteImport
      parentRoute: typeof AuthenticatedInboxRoute
    }
    '/_authenticated/inbox/$conversationId': {
      id: '/_authenticated/inbox/$conversationId'
      path: '/$conversationId'
      fullPath: '/inbox/$conversationId'
      preLoaderRoute: typeof AuthenticatedInboxConversationIdRouteImport
      parentRoute: typeof AuthenticatedInboxRoute
    }
    '/api/public/hooks/automation-event': {
      id: '/api/public/hooks/automation-event'
      path: '/api/public/hooks/automation-event'
      fullPath: '/api/public/hooks/automation-event'
      preLoaderRoute: typeof ApiPublicHooksAutomationEventRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/automation-tick': {
      id: '/api/public/hooks/automation-tick'
      path: '/api/public/hooks/automation-tick'
      fullPath: '/api/public/hooks/automation-tick'
      preLoaderRoute: typeof ApiPublicHooksAutomationTickRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedInboxRouteChildren {
  AuthenticatedInboxConversationIdRoute: typeof AuthenticatedInboxConversationIdRoute
  AuthenticatedInboxIndexRoute: typeof AuthenticatedInboxIndexRoute
}

const AuthenticatedInboxRouteChildren: AuthenticatedInboxRouteChildren = {
  AuthenticatedInboxConversationIdRoute: AuthenticatedInboxConversationIdRoute,
  AuthenticatedInboxIndexRoute: AuthenticatedInboxIndexRoute,
}

const AuthenticatedInboxRouteWithChildren =
  AuthenticatedInboxRoute._addFileChildren(AuthenticatedInboxRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedCompaniesRoute: typeof AuthenticatedCompaniesRoute
  AuthenticatedContactsRoute: typeof AuthenticatedContactsRoute
  AuthenticatedCustomFieldsRoute: typeof AuthenticatedCustomFieldsRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedFlowsRoute: typeof AuthenticatedFlowsRoute
  AuthenticatedInboxRoute: typeof AuthenticatedInboxRouteWithChildren
  AuthenticatedIntegrationsRoute: typeof AuthenticatedIntegrationsRoute
  AuthenticatedMediaRoute: typeof AuthenticatedMediaRoute
  AuthenticatedSegmentsRoute: typeof AuthenticatedSegmentsRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedTagsRoute: typeof AuthenticatedTagsRoute
  AuthenticatedTemplatesRoute: typeof AuthenticatedTemplatesRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedCompaniesRoute: AuthenticatedCompaniesRoute,
  AuthenticatedContactsRoute: AuthenticatedContactsRoute,
  AuthenticatedCustomFieldsRoute: AuthenticatedCustomFieldsRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedFlowsRoute: AuthenticatedFlowsRoute,
  AuthenticatedInboxRoute: AuthenticatedInboxRouteWithChildren,
  AuthenticatedIntegrationsRoute: AuthenticatedIntegrationsRoute,
  AuthenticatedMediaRoute: AuthenticatedMediaRoute,
  AuthenticatedSegmentsRoute: AuthenticatedSegmentsRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedTagsRoute: AuthenticatedTagsRoute,
  AuthenticatedTemplatesRoute: AuthenticatedTemplatesRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface AuthRouteChildren {
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
  AuthIndexRoute: typeof AuthIndexRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
  AuthIndexRoute: AuthIndexRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  ApiPublicHooksAutomationEventRoute: ApiPublicHooksAutomationEventRoute,
  ApiPublicHooksAutomationTickRoute: ApiPublicHooksAutomationTickRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
